### ISSUE TITLE
Handling indirect dependencies on jQuery

### ISSUE THREAD

**Issue by optilude** [thereactivestack/meteor-react-router-ssr#14]
I have an app with a layout based on https://github.com/thereactivestack/kickstart-simple.

It uses React, but depends on a third party library that in turn depends on `jquery` from npm. This isn't actually used during the initial rendering, though.

In webpack.config, I've done the following:

```
  externals: {
    // Make sure we use Meteor package for react and react-router
    'react': 'React',
    'react-router': 'ReactRouter',
    'react-dom': 'ReactDOM',
    'react-addons-transition-group': 'React.addons.TransitionGroup',
    'react-addons-create-fragment': 'React.addons.createFragment',
    'react-addons-pure-render-mixin': 'React.addons.PureRenderMixin',
    'react-addons-update': 'React.addons.update',
    'react-addons-linked-state-mixin': 'React.addons.PureRenderMixin',
    'jquery': 'jQuery'
  },
```

That makes it work client-side (`jQuery` is defined by Meteor via the `jquery` package).

In production mode, when ReactRouterSSR is enabled, I get a build error like `jQuery not defined`.

Is there a way to do this?

**Comment by eXon** [comment]
Have you tried: `'jquery': '$'` instead?

**Comment by optilude** [comment]
Same result.

I am experimenting with this though:

```
if (process.env.NODE_ENV === 'production') {
    global.jQuery = {};
    ReactRouterSSR.LoadWebpackStats(WebpackStats);
}
```

Kind of a hack!

I was wondering if it would work to actually let the server side version use `jquery` from npm and for the client side version to use the one from Meteor, but I couldn't figure out how to convince webpack to do that, if indeed it's possible.

**Comment by optilude** [comment]
Mmm, so that does make it build without error, but when I try to load the page I get:

```
W20151031-22:28:40.841(0)? (STDERR) Warning: React.renderToString is deprecated. Please use ReactDOMServer.renderToString from require('react-dom/server') instead.
W20151031-22:28:40.876(0)? (STDERR) TypeError: Cannot read property 'assetsByChunkName' of null
W20151031-22:28:40.876(0)? (STDERR)     at ServerResponse.res.write (packages/reactrouter_react-router-ssr/lib/server.jsx.js:141:1)
W20151031-22:28:40.876(0)? (STDERR)     at Object.handle (packages/webapp/webapp_server.js:717:1)
W20151031-22:28:40.876(0)? (STDERR)     at next (/Users/maraspeli/.meteor/packages/webapp/.1.2.3.bjo38q++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20151031-22:28:40.876(0)? (STDERR)     at next (/Users/maraspeli/.meteor/packages/webapp/.1.2.3.bjo38q++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:192:9)
W20151031-22:28:40.876(0)? (STDERR)     at next (/Users/maraspeli/.meteor/packages/webapp/.1.2.3.bjo38q++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:127:23)
W20151031-22:28:40.876(0)? (STDERR)     at packages/reactrouter_react-router-ssr/lib/server.jsx.js:163:1
W20151031-22:28:40.876(0)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
W20151031-22:28:40.877(0)? (STDERR)     at Object.handle (packages/meteor/dynamics_nodejs.js:123:1)
W20151031-22:28:40.877(0)? (STDERR)     at next (/Users/maraspeli/.meteor/packages/webapp/.1.2.3.bjo38q++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20151031-22:28:40.877(0)? (STDERR)     at Function.app.handle (/Users/maraspeli/.meteor/packages/webapp/.1.2.3.bjo38q++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:198:3)
```

**Comment by eXon** [comment]
Are you using webpack:webpack with it? What is your webpack.conf.js? I'll need to see more of your project to know why WebpackStats is null.

**Comment by optilude** [comment]
Hi,


This is based on `kickstart-simple`.

`entry.webpack.conf.js`:

```
/* global require, module, __dirname */

var webpack = require('webpack');
var path = require('path');

module.exports = {
  externals: {
    // Make sure we use Meteor package for react and react-router
    'react': 'React',
    'react-router': 'ReactRouter',
    'react-dom': 'ReactDOM',
    'react-addons-transition-group': 'React.addons.TransitionGroup',
    'react-addons-create-fragment': 'React.addons.createFragment',
    'react-addons-pure-render-mixin': 'React.addons.PureRenderMixin',
    'react-addons-update': 'React.addons.update',
    'react-addons-linked-state-mixin': 'React.addons.PureRenderMixin',
    'jquery': 'jQuery'
  },
  devServer: {
    // You can change this to your server IP address to access it remotely
    host: 'localhost'
  },
  resolve: {
    root: path.join(__dirname, '..', 'modules'),
    extensions: ['', '.js', '.jsx', '.json', '.css', '.scss']
  }
};
```

`server/webpack.conf.js`:

```
/* global require, module */

var webpack = require('webpack');

module.exports = {
    entry: './entry',
    module: {
        loaders: [
            { test: /\.jsx?$/, loader: 'babel', query: { stage: 0 }, exclude: /node_modules/ },
            { test: /\.css$/, loader: 'style-collector!css' },
            { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
            { test: /\.(svg|ttf|woff|eot)(\?.*)?$/, loader: 'file' }
        ]
    }
};
```

`client/webpack.conf.js`:

```
/* global require, process, module */

var webpack = require('webpack');
var babelSettings = { stage: 0 };

if(process.env.NODE_ENV !== 'production') {
    babelSettings.plugins = ['react-transform'];
    babelSettings.extra = {
        'react-transform': {
            transforms: [{
                transform: 'react-transform-hmr',
                imports: ['react'],
                locals: ['module']
            }, /* {
                transform: 'react-transform-catch-errors',
                imports: ['react' /'redbox-react' ]
            } */
            ]

    }
  };
}

module.exports = {
    entry: './entry',
    module: {
        loaders: [
            { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
            { test: /\.css$/, loader: 'style!css' },
            { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
            { test: /\.(svg|ttf|woff|eot)(\?.*)?$/, loader: 'file' }
        ]
    }
};

```

**Comment by eXon** [comment]
For jQuery, I'm not sure what you are trying to do with it on the server. Outside of a few util functions (that lodash also have anyways), you don't have a DOM on the server. You have to make sure all your jQuery calls are not going to be called within the first render and componentWillMount.

**Comment by optilude** [comment]
Yeah, I understand. It's a silly transitive dependency (I think it might be `bootbox`, which frankly I could replace with something better for React). It should be fine but I agree it is brittle.

I suspect the error above is nothing to do with that though?

**Comment by eXon** [comment]
The object WebpackStats is automatically defined by the webpack package. If you do a console.log, is it defined?

Are you also making sure you are not calling ReactRouterSSR.Run before the LoadWebpackStats?

**Comment by optilude** [comment]
Here is `entry/server/entry.js`:

/* global process, ReactRouterSSR, WebpackStats, require, global */

// Trigger globals / methods
import 'simon/server/startup'

```
// Do server-rendering only in production mode
if (process.env.NODE_ENV === 'production') {
    global.jQuery = {}; // hack to let server side routing work
    ReactRouterSSR.LoadWebpackStats(WebpackStats);

    require('../client/routes');
}
```

**Comment by optilude** [comment]
A thought: Is `WebpackStats` only set in production mode? Because in my testing of this, I commented out the `if` statement rather than rebuild the entire app in production mode. Maybe that's not supported?

**Comment by optilude** [comment]
And yes, it is `null` when I log like this:

```
/* global process, ReactRouterSSR, WebpackStats, require, global */

// Trigger globals / methods
import 'simon/server/startup'

// Do server-rendering only in proudction mode
// if (process.env.NODE_ENV === 'production') {

    console.log("WebpackStats");
    console.log(WebpackStats);

    global.jQuery = {}; // hack to let server side routing work
    ReactRouterSSR.LoadWebpackStats(WebpackStats);

    require('../client/routes');
// }

```

**Comment by eXon** [comment]
If you do SSR, it means the server has to reload everytime you change a React component. It means the hot reload with no page refresh will not be working.

You can test your app with SSR by doing: `meteor --production`. Then, the WebpackStats should be defined. Have you tried it?

**Comment by optilude** [comment]
I haven't (just logged off, so will try tomorrow).




I was only temporarily testing SSR so I thought it'd just remove the check for prod mode whilst I was testing and force SSR each time.




If it happens that WebpackStats is only defined in prod mode then that would explain it.


Will check tomorrow and comment further. Thanks!





—

**Comment by optilude** [comment]
So, running in `--production` mode seems to help. `WebpackStats` is defined and server rendering works.

However, I am getting some errors in the console, like:

```
=> Meteor server restarted                    
=> Started your app.

=> App running at: http://localhost:3000/
I20151101-20:16:19.213(0)? WebpackStats
I20151101-20:16:19.214(0)? { publicPath: '/assets/',
I20151101-20:16:19.214(0)?   assetsByChunkName: { main: [ 'web.js', 'web.js.map' ] } }
W20151101-20:17:49.472(0)? (STDERR) error while server-rendering TypeError: Cannot call method 'ready' of undefined
W20151101-20:17:49.473(0)? (STDERR)     at [object Object].u.value (webpack:///Users/maraspeli/Development/JavaScript/simon/app/modules/simon/client/components/upload.jsx:10:28)
W20151101-20:17:49.473(0)? (STDERR)     at MeteorDataManager.calculateData (meteor-data-mixin.jsx:62:24)
W20151101-20:17:49.473(0)? (STDERR)     at [object Object].ReactMeteorData.componentWillMount (meteor-data-mixin.jsx:5:45)
W20151101-20:17:49.473(0)? (STDERR)     at [object Object].<anonymous> (webpack:///Users/maraspeli/Development/JavaScript/simon/app/.meteor/local/webpack-npm/~/lodash-compat/lang/isFunction.js:38:1)
W20151101-20:17:49.473(0)? (STDERR)     at [object Object].<anonymous> (webpack:///Users/maraspeli/Development/JavaScript/simon/app/.meteor/local/webpack-npm/~/lodash-compat/lang/isFunction.js:38:1)
W20151101-20:17:49.473(0)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (../../../../../Development/JavaScript/simon/app/react/lib/ReactCompositeComponent:210:1)
W20151101-20:17:49.473(0)? (STDERR)     at Object.ReactReconciler.mountComponent (../../../../../Development/JavaScript/simon/app/react/lib/ReactReconciler:37:1)
W20151101-20:17:49.473(0)? (STDERR)     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (../../../../../Development/JavaScript/simon/app/react/lib/ReactMultiChild:241:1)
W20151101-20:17:49.474(0)? (STDERR)     at ReactDOMComponent.Mixin._createContentMarkup (../../../../../Development/JavaScript/simon/app/react/lib/ReactDOMComponent:588:1)
W20151101-20:17:49.474(0)? (STDERR)     at ReactDOMComponent.Mixin.mountComponent (../../../../../Development/JavaScript/simon/app/react/lib/ReactDOMComponent:478:1)
I20151101-20:17:50.578(0)? Exception from sub meteor.loginServiceConfiguration id T7T8ysLpnXiXB2Rt8 TypeError: Object [object global] has no method '_getFindSelector'
I20151101-20:17:50.578(0)?     at _.extend.find (packages/mongo/collection.js:283:1)
I20151101-20:17:50.579(0)?     at [object Object].Mongo.Collection.find (packages/reactrouter_react-router-ssr/lib/server.jsx.js:225:1)
I20151101-20:17:50.579(0)?     at [object Object].accounts._server.publish.is_auto [as _handler] (accounts_server.js:696:48)
I20151101-20:17:50.579(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151101-20:17:50.579(0)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151101-20:17:50.579(0)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151101-20:17:50.579(0)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151101-20:17:50.580(0)?     at livedata_server.js:548:43
I20151101-20:17:50.588(0)? Exception from sub meteor_autoupdate_clientVersions id xvS3q4jSJApAaMY5j TypeError: Object [object global] has no method '_getFindSelector'
I20151101-20:17:50.588(0)?     at _.extend.find (packages/mongo/collection.js:283:1)
I20151101-20:17:50.589(0)?     at [object Object].Mongo.Collection.find (packages/reactrouter_react-router-ssr/lib/server.jsx.js:225:1)
I20151101-20:17:50.589(0)?     at [object Object].Meteor.publish.is_auto [as _handler] (packages/autoupdate/autoupdate_server.js:155:1)
I20151101-20:17:50.589(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151101-20:17:50.589(0)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151101-20:17:50.589(0)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151101-20:17:50.590(0)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151101-20:17:50.590(0)?     at livedata_server.js:548:43
I20151101-20:17:50.593(0)? Exception from sub roles id kHHHtBBeZoyi5oHx2 TypeError: Object [object global] has no method '_getFindSelector'
I20151101-20:17:50.594(0)?     at _.extend.find (packages/mongo/collection.js:283:1)
I20151101-20:17:50.594(0)?     at [object Object].Mongo.Collection.find (packages/reactrouter_react-router-ssr/lib/server.jsx.js:225:1)
I20151101-20:17:50.594(0)?     at [object Object].Meteor.methods.deleteUser [as _handler] (packages/mrt_accounts-admin-ui-bootstrap-3/packages/mrt_accounts-admin-ui-bootstrap-3.js:71:1)
I20151101-20:17:50.594(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151101-20:17:50.595(0)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151101-20:17:50.595(0)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151101-20:17:50.595(0)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151101-20:17:50.595(0)?     at livedata_server.js:548:43
I20151101-20:18:56.637(0)? Exception from sub meteor_autoupdate_clientVersions id wjmRAPLYJidYKMxkX TypeError: Object [object global] has no method '_getFindSelector'
I20151101-20:18:56.637(0)?     at _.extend.find (packages/mongo/collection.js:283:1)
I20151101-20:18:56.637(0)?     at [object Object].Mongo.Collection.find (packages/reactrouter_react-router-ssr/lib/server.jsx.js:225:1)
I20151101-20:18:56.637(0)?     at [object Object].Meteor.publish.is_auto [as _handler] (packages/autoupdate/autoupdate_server.js:155:1)
I20151101-20:18:56.638(0)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151101-20:18:56.638(0)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151101-20:18:56.638(0)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151101-20:18:56.638(0)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151101-20:18:56.638(0)?     at livedata_server.js:548:43
```

The line at `modules/simon/client/components/upload.jsx:10:28` is just `export default class Upload extends Component {`.

These errors seem to happen only after a hard reload in the browser, and the app appears to work fine. In the browser, it corresponds to a console error `autoupdate subscription failed: ` which then just lists a 500 error (no real context).

Martin

**Comment by eXon** [comment]
It's hard to tell without a few snippets of your code. Can you share a project or a few relevant files?

**Comment by optilude** [comment]
If you're interested enough to try to run it locally, I can share the code with you in its entirety. I can't put it on Github, but I could send it to you privately. Appreciate this requires a bigger time commitment, so up to you! If you want to, let me know how best to send it to you.

**Comment by eXon** [comment]
Send it to me by e-mail at trembl.ben@gmail.com and when I have time I'll take a look.

**Comment by optilude** [comment]
Sent! Thank you!

**Comment by eXon** [comment]
I had a similar problem with one of my project. It should be fixed in the last release. Let me know if it works!

**Comment by minfawang** [comment]
Just an interesting note. When I first run my application in production mode (`meteor --production`), I got a quite similar error as [this](https://github.com/thereactivestack/meteor-react-router-ssr/issues/14#issuecomment-152860927). Then I tried to reproduce this issue. But when I kill the program and re-run it (without changing anything and call the same command `meteor --production`), the error is gone.

I don't know what magic happened and am not sure this response might help. Hope it could provide a little info.

**Comment by john-osullivan** [comment]
Hey @eXon , it looks like this guy has the same sort of issue I do.  I can't figure out where my indirect dependencies are getting triggered from anymore because I've tried to comment most of them out.  Only React code is appearing in the stack trace, but the bug persists.

I tried adding the `global.jQuery = {};` line before loading webpack stats in `./entry/server/entry.js`, but just got a new error:
```
ReferenceError: window is not defined.
```

The `webpack.conf.js` file no longer exports the "externals" key where I previously might have put `'jquery':'$'` line.  How do you recommend I get jQuery accessible to the code?

**Comment by eXon** [comment]
Thanks for noticing. I'll try to take a look asap.

**Comment by john-osullivan** [comment]
Thanks so much!  Both for helping with this bug specifically and for making these repos generally.  You're a hero, I don't know where I'd be without your libraries.

**Comment by eXon** [comment]
@john-osullivan Much appreciated. Do you have a project you can send me to reproduce your problem? I want to see if the new release will fix your problem.

**Comment by john-osullivan** [comment]
Hi @eXon -- I'm not sure where the bug is originating from, so reducing the code to the smallest test case probably won't work.  I think the most effective strategy would be to add you as a collaborator to the main project my team and I are working on.  It's currently set as private, you should receive the share notification within soon.  Thanks for taking a look!

**Comment by eXon** [comment]
This should be working with the last version of webpack / react-router-ssr
